runtime: python39
entrypoint: streamlit run src/app.py --server.port $PORT

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

env_variables:
  STREAMLIT_SERVER_PORT: $PORT

handlers:
- url: /.*
  script: auto 